// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUmCGfFoOOpS_HBtAPSxDzIWaa0ZDGLEM',
    appId: '1:562652923662:web:37d6fb3aa89e4fec2af95f',
    messagingSenderId: '562652923662',
    projectId: 'library-management-62a58',
    authDomain: 'library-management-62a58.firebaseapp.com',
    databaseURL: 'https://library-management-62a58-default-rtdb.firebaseio.com',
    storageBucket: 'library-management-62a58.appspot.com',
    measurementId: 'G-PSM219DWK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvlx3kYUZ6weF5xaj5pQB-T5p9yD3FX4M',
    appId: '1:562652923662:android:affa41b1d2caf0642af95f',
    messagingSenderId: '562652923662',
    projectId: 'library-management-62a58',
    databaseURL: 'https://library-management-62a58-default-rtdb.firebaseio.com',
    storageBucket: 'library-management-62a58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-QL_OSXp7e5-IeHLL7W-lTmUPp2cph3Y',
    appId: '1:562652923662:ios:3556a6121e5a0e1c2af95f',
    messagingSenderId: '562652923662',
    projectId: 'library-management-62a58',
    databaseURL: 'https://library-management-62a58-default-rtdb.firebaseio.com',
    storageBucket: 'library-management-62a58.appspot.com',
    iosClientId: '562652923662-n02a3aj31li3c7ir89srd07ntlei5het.apps.googleusercontent.com',
    iosBundleId: 'com.example.libManage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-QL_OSXp7e5-IeHLL7W-lTmUPp2cph3Y',
    appId: '1:562652923662:ios:3556a6121e5a0e1c2af95f',
    messagingSenderId: '562652923662',
    projectId: 'library-management-62a58',
    databaseURL: 'https://library-management-62a58-default-rtdb.firebaseio.com',
    storageBucket: 'library-management-62a58.appspot.com',
    iosClientId: '562652923662-n02a3aj31li3c7ir89srd07ntlei5het.apps.googleusercontent.com',
    iosBundleId: 'com.example.libManage',
  );
}
